Ik heb communicatie met de arduino gemaakt en het begin van communica…
stijnvdelsen/recycle_api pull request #3
Opened 2021-11-04 13:33 UTC by LukeSteegh

…tie met de server.

2021-11-04 13:36 UTC, AsterosTheGreat approved these changes
return points moet nog een keer vervangen worden met server communicatie.

2021-11-05 08:24 UTC, stijnvdelsen requested changes

2021-11-05 08:24 UTC, stijnvdelsen commented on main.py
> +def arduinoResponse():
Goed om die naam aan te passen naar savePoints imo.

2021-11-05 12:17 UTC, stijnvdelsen approved these changes

2021-11-05 12:17 UTC, merged